name: Generate Snake Animation

on:
  schedule: # every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: HasanSattar
          outputs: |
            dist/snake.svg
            dist/snake.gif
            dist/snake-dark.svg
            dist/snake-dark.gif

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
